#!/bin/bash

WALLETPATH=/workspace

if [ -z "$1" ]; then
    for i in 1 2 3 4
    do
        cd $WALLETPATH/w$i    
        tagionwallet --update >/dev/null
        balance=$(tagionwallet --amount)
        echo "Wallet "$i": "$balance
        
    done
else
    cd $WALLETPATH/$1
    tagionwallet --update >/dev/null
    tagionwallet --amount
fi